### ISSUE TITLE
Send logs to syslog

### ISSUE THREAD

**Issue by utdrmac** [tomochain/goutte#13]
Would love to see an option to send log output to syslog instead of stdout

**Comment by etienne-napoleone** [comment]
If you are running it natively, you can pipe it to `logger` ([manpage](https://linux.die.net/man/1/logger)).
If you are running it through its docker image, you can configure the login driver for this container or the whole docker daemon ([docs](https://docs.docker.com/config/containers/logging/configure/)).

There is no plan for integrating it directly into the software as it's quite easy to interface it.
