### ISSUE TITLE
A very novice question

### ISSUE THREAD

**Issue by FreeWoRLD83** [tomochain/goutte#14]
```python3.5 goutte goutte.toml 123api456 --only snapshot```

This is what I get;

```
user@server:~/.local/bin$ python3.5 goutte GOUTTE_CONFIG
Traceback (most recent call last):
  File "goutte", line 7, in <module>
    from goutte.main import entrypoint
  File "/home/user/.local/lib/python3.5/site-packages/goutte/main.py", line 34
    log.debug(f'Retention is set to {conf["retention"]} snapshots')
                                                                 ^
SyntaxError: invalid syntax

```

What am I doing wrong here (as a novice)?

**Comment by etienne-napoleone** [comment]
You are running it with Python 3.5, Goutte only [support](https://github.com/tomochain/goutte#requirements) 3.6+
Python 3.5 doesn't support [f-strings](https://www.python.org/dev/peps/pep-0498/) and therefore raise this error.

Try updating to python 3.6 or 3.7 (see virtual environments)
