### ISSUE TITLE
Snapshot Retention Period 

### ISSUE THREAD

**Issue by biswajitban** [tomochain/goutte#15]
Thanks for wonderful script . Snapshot Backup for Droplet and Volume is working fine .
My question is for retention period
I have kept the retention period as 2 days in goutte.toml but Snapshots keeps on accumulating and does not get deleted .
Can some light be thrown how snapshots older that 2 days be deleted automatically .

TIA

**Comment by etienne-napoleone** [comment]
Thanks for the kind word!
Can you show me the output of the command ran with the `--debug` flag when it should be supposed to prune snapshots?

**Comment by etienne-napoleone** [comment]
Closed for inactivity, feel free to reopen

**Comment by etienne-napoleone** [comment]
Closed for inactivity
